favicon: /img/favicon.jpg
# Change to your profile picture
# avatar: https://pl.cs.pku.edu.cn/__local/1/5F/B4/46C04EFA338A04BE006D6ED7BAC_E02FC66C_392FF.jpg
# if author sets in hexo_config, this string doesn't work
author: 'Qihao LIAN'
author_bio: 'Ph.D. student in Programming Language.'

since: 2023

# Top Menu 顶部菜单
# #title 为页内跳转，单页模式
# 可以选择外链或其他页面
menu:
  Publications: /publications
  Notes: /notes
  # About: /about
  # Blog: /

# flink picture will load if avator link calls on error
loading_bg:
  flink: /img/profile.png

# Social Links; 社交链接，不需要的链接直接注释掉
# 可以调整显示顺序
# 图标调用 font-awesome 4.7
social:
  enable: true
social_links:
  # fab fa-twitter: /
  # fab fa-facebook-square: /
  fab fa-github: https://github.com/Mepy
  # fab fa-stack-overflow: /
  # fab fa-linkedin: /
  # fab fa-weibo: /
  # fab fa-weixin: /
  # fab fa-qq: /
  fas fa-envelope: mailto://mepy@stu.pku.edu.cn #E-mail
  # fas fa-rss: /  #rss

# Additional social_links，额外添加自定义链接，可显示链接名称
# name: url || icon_name
e_social:
  enable: false
e_social_links:
  Google Scholar: / || fas fa-graduation-cap
  ORCID: / || fab fa-orcid

# CV download link
cv_dl:
  enable: false
  dir: /attaches/CV.pdf
  description: My Detail CV.

# Box-shadow
# display box-shadow on page or not
box_shadow:
  enable: true

# CDN
# 根据需要自行添加js/css
# 自定义css可以直接写在user.styl中
CDN_USE:
  css:
    - /css/index.css
#    - https://cdn.jsdelivr.net/npm/font-awesome@latest/css/font-awesome.min.css
    - https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.13.0/css/all.min.css # fontawesome 5
  js:
    - https://cdn.jsdelivr.net/npm/jquery@latest/dist/jquery.min.js #/js/third-party/jquery.min.js
    - https://cdn.jsdelivr.net/npm/jquery-pjax@latest/jquery.pjax.min.js
    - /js/main.js